[build]
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "https://threed-agentic-twins-v2-0.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
