[build]
  # If your site is just static HTML/JS, publish the frontend folder
  publish = "frontend"
  # If you have a bundler (React/Vite), adjust the command here
  # command = "npm run build"

# Proxy all API requests from Netlify → Render backend
[[redirects]]
  from = "/api/*"
  to = "https://threed-agentic-twins-v2-0.onrender.com/api/:splat"
  status = 200
  force = true

# Fallback for SPAs (safe even for plain HTML)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
